countries=c("Afeganistão"="AF","África do Sul"="ZA","Albânia"="AL","Alemanha"="DE","Andorra"="AD","Angola"="AO",
            "Anguila"="AI","Antiga e Barbuda"="AG","Antilhas Holandesas"="AN","Arábia Saudita"="SA",
            "Argélia"="DZ","Argentina"="AR","Arménia"="AM","Aruba"="AW","Austrália"="AU","Áustria"="AT",
            "Azerbaijão"="AZ","Bahamas"="BS","Bangladexe"="BD","Barbados"="BB","Barém"="BH","Bélgica"="BE",
            "Belize"="BZ","Benim"="BJ","Bermuda"="BM","Bielorrússia"="BY","Bolívia"="BO","Bonaire"="XA",
            "Bósnia e Herzegovina"="BA","Botsuana"="BW","Brasil"="BR","Brunei"="BN","Bulgária"="BG",
            "Burquina Faso"="BF","Burúndi"="BI","Butão"="BT","Cabo Verde"="CV","Camarões"="CM","Camboja"="KH",
            "Canadá"="CA","Catar"="QA","Cazaquistão"="KZ","Chade"="TD","Chile"="CL","China"="CN","Chipre"="CY",
            "Colômbia"="CO","Comores"="KM","Congo"="CG","Coreia do Norte"="KP","Coreia do Sul"="KR",
            "Costa do Marfim"="CI","Costa Rica"="CR","Croácia"="HR","Cuaite"="KW","Cuba"="CU","Curaçao"="CW",
            "Dinamarca"="DK","Djibouti"="DJ","Dominica"="DM","Egito"="EG","El Salvador"="SV",
            "Emirados Árabes Unidos"="AE","Equador"="EC","Eritreia"="ER","Eslováquia"="SK","Eslovénia"="SI",
            "Espanha"="ES","Estados Unidos"="US","Estônia"="EE","Etiópia"="ET","Fiji"="FJ","Filipinas"="PH",
            "Finlândia"="FI","França"="FR","Gabão"="GA","Gâmbia"="GM","Gana"="GH","Geórgia"="GE","Gibraltar"="GI",
            "Granada"="GD","Grécia"="GR","Guadalupe"="GP","Guatemala"="GT","Guiana"="GY","Guiana Francesa"="GF",
            "Guiné"="GN","Guiné Equatorial"="GQ","Guiné-Bissau"="GW","Haiti"="HT","Honduras"="HN","Hong Kong"="HK",
            "Hungria"="HU","Iémen"="LB","Iêmen"="YE","Ilha de Man"="IM","Ilha de São Martinho"="MF","Ilhas Cayman"="KY",
            "Ilhas Cook"="CK","Ilhas Malvinas"="FK","Ilhas Marechal"="MH","Ilhas Salomão"="SB",
            "Ilhas Turcas e Caicos"="TC","Ilhas Virgens Americanas"="VI","Ilhas Virgens Britânicas"="VG",
            "Índia"="IN","Indonésia"="ID","Irão"="IR","Iraque"="IQ","Irlanda"="IE","Islândia"="IS","Israel"="IL",
            "Itália"="IT","Iugoslávia"="YU","Jamaica"="JM","Japão"="JP","Jordânia"="JO","Laus"="LA","Lesoto"="LS",
            "Letônia"="LV","Líbano"="LR","Líbia"="LY","Liechtenstein"="LI","Lituânia"="LT","Luxemburgo"="LU",
            "Macedónia do Norte"="MK","Madagascar"="MG","Malásia"="MY","Maláui"="MW","Maldivas"="MV","Mali"="ML",
            "Malta"="MT","Marrocos"="MA","Martinica"="MQ","Maurícia"="MU","Mauritânia"="MR","Melilha"="EA",
            "México"="MX","Mianmar"="MM","Micronésia"="FM","Moçambique"="MZ","Moldávia"="MD","Mónaco"="MC",
            "Mongólia"="MN","Montenegro"="ME","Montserrat"="MS","Namíbia"="NA","Nauru"="NR","Nepal"="NP",
            "Nicarágua"="NI","Níger"="NE","Nigéria"="NG","Niue"="NU","Noruega"="NO","Nova Caledônia"="NC",
            "Nova Zelândia"="NZ","Omã"="OM","Países Baixos"="NL","Palau"="PW","Panamá"="PA","Papua Nova Guiné"="PG",
            "Paquistão"="PK","Paraguai"="PY","Peru"="PE","Polónia"="PL","Porto Rico"="PR","Portugal"="PT",
            "Quénia"="KE","Quirguistão"="KG","Quiribáti"="KI","Reino Unido"="GB","República Centro-Africana"="CF",
            "República Checa"="CZ","República Democrática do Congo"="CD","República Dominicana"="DO","Roménia"="RO",
            "Ruanda"="RW","Rússia"="RU","Saba"="XC","Samoa"="WS","Santa Lúcia"="LC","Santo Eustáquio"="XB",
            "São Bartolomeu"="BL","São Cristóvão e Neves"="KN","São Marinho"="SM","São Martinho"="SX",
            "São Pedro e Miquelão"="PM","São Tomé e Príncipe"="ST","São Vicente e Granadinas"="VC",
            "Seicheles"="SC","Senegal"="SN","Serra Leoa"="SL","Sérvia"="RS","Singapura"="SG","Síria"="SY",
            "Somália"="SO","Sri Lanca"="LK","Suazilândia"="SZ","Sudão"="SD","Sudão do Sul"="SS","Suécia"="SE",
            "Suíça"="CH","Suriname"="SR","Tailândia"="TH","Taiwan"="TW","Tajiquistão"="TJ","Tanzânia"="TZ",
            "Timor-Leste"="TL","Togo"="TG","Tonga"="TO","Trindade e Tobago"="TT","Tunísia"="TN","Turcomenistão"="TM",
            "Turquia"="TR","Tuvalu"="TV","Ucrânia"="UA","Uganda"="UG","Uruguai"="UY","Usbequistão"="UZ","Vanuatu"="VU",
            "Venezuela"="VE","Vietname"="VN","Wallis e Futuna"="WF","Zâmbia"="ZM","Zimbábue"="ZW","Não informado")